version: '3'
services:
  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - localnet
  mysql:
    image: mysql:8.1
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: junction
    ports:
      - "3306:3306"
    networks:
      - localnet

networks:
  localnet:
    attachable: true